[package]
name = "hpc-core"
version = "0.1.0"
edition = "2024"

[dependencies]
opencl3 = "0.7"
thiserror = "1"
bytemuck  = "1.14"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "vec_add_bench"
harness = false

